In [1]:
import numpy as np 

In [2]:
numpy_arr = np.array([x for x in range(1,10)])

In [3]:
numpy_arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
numpy_arr.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
numpy_arr = np.array([x for x in range(1,13)])

In [8]:
numpy_arr.reshape(2,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [9]:
numpy_arr.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

In [14]:
numpy_arr = numpy_arr.reshape(2,2,-1)

In [15]:
numpy_arr

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [16]:
numpy_arr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [2]:
numpy_arr = np.arr([x for x in range(1,20)])

NameError: name 'np' is not defined

In [3]:
import numpy as np


In [4]:
numpy_arr = np.arr([x for x in range(1,15)])

AttributeError: module 'numpy' has no attribute 'arr'