In [1]:
import numpy as np

In [2]:
array_1d = np.array([5,6,8])
array_2d = np.array([[2,5,6],[5,7,2]])
array_3d = np.array([[[3,5,3],[4,6,8],[5,4,3]]])

In [3]:
array_2d

array([[2, 5, 6],
       [5, 7, 2]])

In [4]:
array_3d

array([[[3, 5, 3],
        [4, 6, 8],
        [5, 4, 3]]])

In [5]:
array_1d

array([5, 6, 8])

In [6]:
array_1d[0]

5